AWSTemplateFormatVersion: "2010-09-09"

Resources:
  TerraformS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: terraformtestdeploy

Outputs:
  S3BucketName:
    Value: !Ref TerraformS3Bucket
    Description: Name of the created S3 bucket
