AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for VPC and Subnet

Resources:
  TerraformSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow SSH access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'

  TerraformSecurityGroupNew1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow SSH access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'  

Outputs:
  SecurityGroupTerraform:
    Description: Subnet ID for TerraformTestSubnet
    Value: !Ref TerraformSecurityGroup

  SecurityGroupTerraformNew1:
    Description: Subnet ID for TerraformTestSubnet
    Value: !Ref TerraformSecurityGroupNew1
